
trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore

    projects: '$(solution)'


- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test

    projects: '**/CyDar.ServiceLocator.Tests.csproj'

    arguments: '--configuration $(buildConfiguration)'


- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(solution)'

    arguments: '--configuration $(buildConfiguration) "/p:AssemblyOriginatorKeyFile=$(build.sourcesDirectory)/CyDar.snk" "/p:SignAssembly=true"'


- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack

    packagesToPack: CyDar.ServiceLocator/CyDar.ServiceLocator.csproj

    nobuild: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: CyDarPack'
  inputs:
    ArtifactName: CyDarPack


- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: push

    nuGetFeedType: external

    publishFeedCredentials: 'NugetOrgConnection'

  enabled: false

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push

    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'

    nuGetFeedType: external

    publishFeedCredentials: 'NugetOrgConnection'